FROM postgres:11
LABEL maintainer="ovidio.zea@gmail.com"

ENV POSTGRES_PASSWORD=postgres123
ENV POSTGRES_DB=tienda
#ENV MYSQL_ROOT_HOST=%

#COPY ./scripts/ /docker-entrypoint-initdb.d/
#CMD ["--default-authentication-plugin=mysql_native_password"]